from enum import StrEnum


class EventType(StrEnum):
    # Occupancy
    OCCUPANCY_UPDATE = "OCCUPANCY_UPDATE"
    OCCUPANCY_THRESHOLD_CROSSED = "OCCUPANCY_THRESHOLD_CROSSED"
    # Alerts
    ALERT_RAISED = "ALERT_RAISED"
    ALERT_RESOLVED = "ALERT_RESOLVED"
    # Congestion
    VESTIBULE_CONGESTION = "VESTIBULE_CONGESTION"
    LUGGAGE_RACK_SATURATION = "LUGGAGE_RACK_SATURATION"
    # Safety
    UNATTENDED_BAG = "UNATTENDED_BAG"
    DOOR_OBSTRUCTION = "DOOR_OBSTRUCTION"
    # Accessibility
    ACCESSIBILITY_DETECTED = "ACCESSIBILITY_DETECTED"
    RAMP_DEPLOYED = "RAMP_DEPLOYED"
    # TCMS / Alarms
    ALARM_ACTIVE = "ALARM_ACTIVE"
    ALARM_CLEARED = "ALARM_CLEARED"
    # Journey
    JOURNEY_STARTED = "JOURNEY_STARTED"
    JOURNEY_ENDED = "JOURNEY_ENDED"
    # System
    CAMERA_DEGRADED = "CAMERA_DEGRADED"
    CAMERA_RECOVERED = "CAMERA_RECOVERED"
    SYNC_COMPLETED = "SYNC_COMPLETED"
    # Inter-wagon movement (ADR-17)
    WAGON_EXIT = "WAGON_EXIT"
    WAGON_ENTRY = "WAGON_ENTRY"
    LEDGER_DRIFT_ALERT = "LEDGER_DRIFT_ALERT"
    # APC calibration drift (ADR-15)
    CALIBRATION_DRIFT = "CALIBRATION_DRIFT"
    # Comfort scoring (ADR-18)
    COACH_COMFORT_INDEX = "COACH_COMFORT_INDEX"
    # Internal stream priority signal (ADR-18; never written to event-store)
    STREAM_PRIORITY = "STREAM_PRIORITY"
