from enum import StrEnum


class EventType(StrEnum):
    # Occupancy
    OCCUPANCY_UPDATE = "OCCUPANCY_UPDATE"
    OCCUPANCY_THRESHOLD_CROSSED = "OCCUPANCY_THRESHOLD_CROSSED"
    # Alerts
    ALERT_RAISED = "ALERT_RAISED"
    ALERT_RESOLVED = "ALERT_RESOLVED"
    # Congestion
    VESTIBULE_CONGESTION = "VESTIBULE_CONGESTION"
    LUGGAGE_RACK_SATURATION = "LUGGAGE_RACK_SATURATION"
    # Safety
    UNATTENDED_BAG = "UNATTENDED_BAG"
    DOOR_OBSTRUCTION = "DOOR_OBSTRUCTION"
    # Accessibility
    ACCESSIBILITY_DETECTED = "ACCESSIBILITY_DETECTED"
    RAMP_DEPLOYED = "RAMP_DEPLOYED"
    # TCMS / Alarms
    ALARM_ACTIVE = "ALARM_ACTIVE"
    ALARM_CLEARED = "ALARM_CLEARED"
    # Journey
    JOURNEY_STARTED = "JOURNEY_STARTED"
    JOURNEY_ENDED = "JOURNEY_ENDED"
    # System
    CAMERA_DEGRADED = "CAMERA_DEGRADED"
    CAMERA_RECOVERED = "CAMERA_RECOVERED"
    SYNC_COMPLETED = "SYNC_COMPLETED"
